services:
  db:
    image: 'postgres:17.5-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=embed_bot
    volumes:
      # Persistence
      - ./docker/db/data/:/var/lib/postgresql/data/
  cache:
    image: 'memcached:1.6.32-alpine'
    ports:
      - 11211:11211
    command:
      -- 'memory-limit=2048'
