services:
  db:
    image: 'postgres:16.4'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=embed_bot
    volumes:
      # Persistence
      - ./docker/db/data/:/var/lib/postgresql/data/
      # Init script
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  cache:
    image: 'memcached:1.6.29'
    ports:
      - 11211:11211
    command:
      -- 'memory-limit=2048'