# Generated by Django 5.0.6 on 2024-07-06 16:21

import bot.common.model_fields
import bot.constants
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ServerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'integration',
                    bot.common.model_fields.StringEnumField(
                        choices=[
                            ('instagram', 'INSTAGRAM'),
                            ('facebook', 'FACEBOOK'),
                            ('tiktok', 'TIKTOK'),
                            ('reddit', 'REDDIT'),
                            ('twitter', 'TWITTER'),
                            ('youtube', 'YOUTUBE'),
                        ],
                        editable=False,
                        enum=bot.constants.Integration,
                        max_length=9,
                    ),
                ),
                ('integration_id', models.CharField(editable=False, max_length=64)),
                ('integration_index', models.PositiveSmallIntegerField(null=True)),
                ('author_id', models.CharField(db_index=True, editable=False, max_length=32)),
                ('url', models.URLField(editable=False, max_length=2000)),
                ('content', models.TextField()),
                ('blob', models.BinaryField(max_length=1048576)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'server_post',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('vendor_uid', models.CharField(editable=False, max_length=32)),
                (
                    'vendor',
                    bot.common.model_fields.StringEnumField(
                        choices=[('discord', 'DISCORD')],
                        default=bot.constants.BotVendor['DISCORD'],
                        enum=bot.constants.BotVendor,
                        max_length=7,
                    ),
                ),
                ('admin_id', models.CharField(db_index=True, editable=False, max_length=32)),
                (
                    'tier',
                    bot.common.model_fields.IntEnumField(
                        choices=[(1, 'FREE'), (2, 'STANDARD'), (3, 'PREMIUM'), (4, 'ULTRA')],
                        default=bot.constants.BotTier['FREE'],
                        enum=bot.constants.BotTier,
                    ),
                ),
                ('tier_valid_until', models.DateTimeField(null=True)),
                (
                    'status',
                    bot.common.model_fields.IntEnumField(
                        choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'BLOCKED')],
                        default=bot.constants.BotStatus['ACTIVE'],
                        enum=bot.constants.BotStatus,
                    ),
                ),
                ('prefix', models.CharField(max_length=1, null=True)),
                ('post_format', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'server',
                'indexes': [models.Index(fields=['tier', 'tier_valid_until'], name='server_tier_a65449_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='server',
            constraint=models.UniqueConstraint(fields=('vendor', 'vendor_uid'), name='vendor_unique_idx'),
        ),
        migrations.AddField(
            model_name='serverpost',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.server'),
        ),
        migrations.AddIndex(
            model_name='serverpost',
            index=models.Index(fields=['server', 'created'], name='server_post_server__0edfec_idx'),
        ),
        migrations.AddConstraint(
            model_name='serverpost',
            constraint=models.UniqueConstraint(
                fields=('integration', 'integration_id', 'integration_index', 'server'), name='integration_unique_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='serverpost',
            constraint=models.UniqueConstraint(fields=('url', 'server'), name='url_unique_idx'),
        ),
    ]
