# Generated by Django 5.0.6 on 2024-07-14 14:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverintegration',
            name='server',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='integrations',
                to='bot.server',
            ),
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vendor_uid', models.CharField(editable=False, max_length=32)),
                ('banned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'server',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.server'
                    ),
                ),
            ],
            options={
                'db_table': 'server_user',
            },
        ),
        migrations.AddConstraint(
            model_name='serveruser',
            constraint=models.UniqueConstraint(fields=('vendor_uid', 'server'), name='vendor_server_unique_idx'),
        ),
    ]
