# Generated by Django 5.1.2 on 2024-10-17 07:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
