# Generated by Django 5.0.6 on 2024-07-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_serverintegration_server_serveruser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerUser',
            new_name='ServerMember',
        ),
        migrations.AlterModelTable(
            name='servermember',
            table='server_member',
        ),
    ]
